### ISSUE TITLE
crash at godebug/astutil.go:79

### ISSUE THREAD

**Issue by glycerine** [mailgun/godebug#4]
on the vagrant box on my mac, running go1.3.3 linux/amd64
I install github.com/glycerine/goq, then try running godebug on it. It crashes as follows:

~~~
vagrant@mailgun-dev:~/goq$ godebug -w .
package main
func main() {defer godebug.SLine(ctx, scope, "<Running deferred function>: defer os.Remove("hi.there")")}panic: 2:\
93: expected ')', found 'IDENT' hi
  
goroutine 16 [running]:
runtime.panic(0x6a4040, 0xc2134e3500)
    /home/vagrant/pkg/go1.3.3/go/src/pkg/runtime/panic.c:279 +0xf5
main.astPrintf(0xc213496c40, 0x3f, 0xc2134e3160, 0x2, 0x2, 0x0, 0x0, 0x0)
    /home/vagrant/go/src/github.com/mailgun/godebug/astutil.go:79 +0x40e
main.(*visitor).Visit(0xc2134e0700, 0x7ffa322e3ef0, 0xc20e43c8b0, 0x0, 0x0)
    /home/vagrant/go/src/github.com/mailgun/godebug/gen.go:622 +0x1a86
go/ast.Walk(0x7ffa322e3fb0, 0xc2134e0700, 0x7ffa322e3ef0, 0xc20e43c8b0)
    /home/vagrant/pkg/go1.3.3/go/src/pkg/go/ast/walk.go:52 +0x58
go/ast.walkStmtList(0x7ffa322e3fb0, 0xc2134e0700, 0xc20985c700, 0x9, 0x10)
    /home/vagrant/pkg/go1.3.3/go/src/pkg/go/ast/walk.go:32 +0xd1
go/ast.Walk(0x7ffa322e3fb0, 0xc2134e0700, 0x7ffa32407850, 0xc20e43e930)
    /home/vagrant/pkg/go1.3.3/go/src/pkg/go/ast/walk.go:224 +0x41e7
go/ast.Walk(0x7ffa322e3fb0, 0xc2134e05b0, 0x7ffa322e42b0, 0xc20e43cad0)
    /home/vagrant/pkg/go1.3.3/go/src/pkg/go/ast/walk.go:98 +0x3587
go/ast.walkExprList(0x7ffa322e3fb0, 0xc2134e0310, 0xc20e2b8280, 0x3, 0x4)
    /home/vagrant/pkg/go1.3.3/go/src/pkg/go/ast/walk.go:26 +0xd1
...
~~~

**Comment by jeremyschlatter** [comment]
@glycerine Thanks for the bug report. I just pushed a patch. Can you verify it fixed the problem?

**Comment by glycerine** [comment]
verified. new issue #5 popped up, but this one is gone.
